run:
  skip-dirs:
    - (^|/)testdata($|/)
  skip-dirs-use-default: false

linters:
  enable:
    - goimports
    - gofmt
    - misspell
    - gosec
    - maligned
    - unconvert
    - golint
    - gocognit
    - gocyclo
  fast: true

linters-settings:
  misspell:
    locale: US
  golint:
    min-confidence: 0
  govet:
    check-shadowing: false
  gocognit:
    min-complexity: 17
  gocyclo:
    min-complexity: 17
  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
